name: dthor

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title

baseurl: "" # subpath of your site
url: "http://dthor.github.io" # the base hostname and protocol for your site

encoding: utf-8
