name: dthor

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title

baseurl: "" # subpath of your site
url: "http://dthor.github.io" # the base hostname and protocol for your site

source: E:/R/github/dthor.github.io
destination: E:/R/github/dthor.github.io 

encoding: utf-8

#~~~~~~~~~~~~~~~~
github: [metadata]
 kramdown:
   input: GFM
   hard_wrap: false
 gems:
   - jekyll-coffeescript
   - jekyll-paginate
