name: dthor

author:
name: Darren Thornbrugh
email: dthornbr@gmail.com
givenName: Darren
familyName: Thornbrugh
publisedName: Darren J. Thornbrugh
github: dthor

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title

baseurl: "" # subpath of your site
url: "http://dthor.github.io" # the base hostname and protocol for your site

header: yes
header_large: images/dee_santiam_river_clip.JPG
header_sm: images/dee_santiam_river_w1375.jpg

title: dthor.github.io
subtitle:
tagline:
description: 

keywords: aquatic, ecology, streams, rivers, freshwater, fish, macroinvertebrates, community ecology, stream ecology, landscape ecology, watershed scientist, geospatial analysis, statistics, googlebb480c3da833821e.html  

# contact and social media links
email: dthornbr@gmail.com
facebook:
researchgate:
googleplus:
google scholar:
mendeley:

source: C:/Users/DThornbrugh/dthor.github.io
destination: C:/Users/DThornbrugh/dthor.github.io/_site 

encoding: utf-8
